TYPE=VIEW
query=select `uasbasisdata2`.`buku`.`idbuku` AS `idbuku`,`uasbasisdata2`.`buku`.`judul` AS `Judul Buku`,`uasbasisdata2`.`pengarang`.`nama` AS `Nama Pengarang`,`uasbasisdata2`.`kelola_pengarang`.`jnskelola` AS `Jenis Kelola Pengarang`,`uasbasisdata2`.`kelola_pengarang`.`tanggal` AS `Tanggal Pengarang`,`uasbasisdata2`.`penerbit`.`penerbit` AS `Nama Penerbit`,`uasbasisdata2`.`kelola_penerbit`.`jnskelola` AS `Jenis Kelola Penerbit`,`uasbasisdata2`.`kelola_penerbit`.`tanggal` AS `Tanggal Penerbit` from (((((`uasbasisdata2`.`buku` join `uasbasisdata2`.`buku_pengarang` on(`uasbasisdata2`.`buku`.`idbuku` = `uasbasisdata2`.`buku_pengarang`.`idbuku`)) join `uasbasisdata2`.`pengarang` on(`uasbasisdata2`.`buku_pengarang`.`idpengarang` = `uasbasisdata2`.`pengarang`.`idpengarang`)) join `uasbasisdata2`.`penerbit` on(`uasbasisdata2`.`buku`.`idpenerbit` = `uasbasisdata2`.`penerbit`.`idpenerbit`)) join `uasbasisdata2`.`kelola_pengarang` on(`uasbasisdata2`.`pengarang`.`idpengarang` = `uasbasisdata2`.`kelola_pengarang`.`idpengarang`)) join `uasbasisdata2`.`kelola_penerbit` on(`uasbasisdata2`.`penerbit`.`idpenerbit` = `uasbasisdata2`.`kelola_penerbit`.`idpenerbit`))
md5=d508390e4f6b4bff18451a4366881380
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=0001751473630710655
create-version=2
source=SELECT\n  buku.idbuku,\n  buku.judul AS \'Judul Buku\',\n  pengarang.nama AS \'Nama Pengarang\',\n  kelola_pengarang.jnskelola AS \'Jenis Kelola Pengarang\',\n  kelola_pengarang.tanggal AS \'Tanggal Pengarang\',\n  penerbit.penerbit AS \'Nama Penerbit\',\n  kelola_penerbit.jnskelola AS \'Jenis Kelola Penerbit\',\n  kelola_penerbit.tanggal AS \'Tanggal Penerbit\'\nFROM buku\nINNER JOIN buku_pengarang ON buku.idbuku = buku_pengarang.idbuku\nINNER JOIN pengarang ON buku_pengarang.idpengarang = pengarang.idpengarang\nINNER JOIN penerbit ON buku.idpenerbit = penerbit.idpenerbit\nINNER JOIN kelola_pengarang ON pengarang.idpengarang = kelola_pengarang.idpengarang\nINNER JOIN kelola_penerbit ON penerbit.idpenerbit = kelola_penerbit.idpenerbit
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `uasbasisdata2`.`buku`.`idbuku` AS `idbuku`,`uasbasisdata2`.`buku`.`judul` AS `Judul Buku`,`uasbasisdata2`.`pengarang`.`nama` AS `Nama Pengarang`,`uasbasisdata2`.`kelola_pengarang`.`jnskelola` AS `Jenis Kelola Pengarang`,`uasbasisdata2`.`kelola_pengarang`.`tanggal` AS `Tanggal Pengarang`,`uasbasisdata2`.`penerbit`.`penerbit` AS `Nama Penerbit`,`uasbasisdata2`.`kelola_penerbit`.`jnskelola` AS `Jenis Kelola Penerbit`,`uasbasisdata2`.`kelola_penerbit`.`tanggal` AS `Tanggal Penerbit` from (((((`uasbasisdata2`.`buku` join `uasbasisdata2`.`buku_pengarang` on(`uasbasisdata2`.`buku`.`idbuku` = `uasbasisdata2`.`buku_pengarang`.`idbuku`)) join `uasbasisdata2`.`pengarang` on(`uasbasisdata2`.`buku_pengarang`.`idpengarang` = `uasbasisdata2`.`pengarang`.`idpengarang`)) join `uasbasisdata2`.`penerbit` on(`uasbasisdata2`.`buku`.`idpenerbit` = `uasbasisdata2`.`penerbit`.`idpenerbit`)) join `uasbasisdata2`.`kelola_pengarang` on(`uasbasisdata2`.`pengarang`.`idpengarang` = `uasbasisdata2`.`kelola_pengarang`.`idpengarang`)) join `uasbasisdata2`.`kelola_penerbit` on(`uasbasisdata2`.`penerbit`.`idpenerbit` = `uasbasisdata2`.`kelola_penerbit`.`idpenerbit`))
mariadb-version=100432
